name: syalo_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  fl_chart: ^0.40.6
  flutter_switch: ^0.3.2
  google_fonts: ^2.1.1
  page_transition: ^2.0.4
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500